/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "background": "#0b1229",
        "surface-variant": "#2d344c",
        "surface-tint": "#eac078",
        "on-secondary-container": "#004c5b",
        "tertiary-container": "#c6a26e",
        "secondary-container": "#00c4e6",
        "tertiary": "#e7c08a",
        "outline-variant": "#4e4639",
        "on-secondary-fixed": "#001f26",
        "primary": "#eac078",
        "primary-container": "#c9a25d",
        "surface-container-high": "#222941",
        "outline": "#9a8f80",
        "on-tertiary-container": "#51380e",
        "on-error": "#690005",
        "on-tertiary-fixed": "#281800",
        "surface-container": "#181e36",
        "inverse-primary": "#78591b",
        "on-tertiary-fixed-variant": "#5c4217",
        "surface-container-lowest": "#060d24",
        "primary-fixed": "#ffdea9",
        "surface": "#0b1229",
        "surface-container-highest": "#2d344c",
        "tertiary-fixed-dim": "#e7c08a",
        "on-tertiary": "#432c03",
        "tertiary-fixed": "#ffddb0",
        "on-primary-fixed-variant": "#5e4203",
        "error": "#ffb4ab",
        "on-primary": "#422d00",
        "on-secondary": "#003641",
        "surface-dim": "#0b1229",
        "secondary-fixed-dim": "#36d8fb",
        "primary-fixed-dim": "#eac078",
        "surface-container-low": "#141a32",
        "secondary-fixed": "#aeecff",
        "on-secondary-fixed-variant": "#004e5d",
        "secondary": "#5bdfff",
        "inverse-on-surface": "#292f48",
        "inverse-surface": "#dce1ff",
        "on-background": "#dce1ff",
        "on-primary-fixed": "#271900",
        "error-container": "#93000a",
        "on-surface": "#dce1ff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#323851",
        "on-primary-container": "#523800",
        "on-surface-variant": "#d1c5b4",
      },
      // ── CRITICAL RADIUS FIX (was 0.75rem which broke all circles) ──
      borderRadius: {
        DEFAULT: "0.125rem",  // 2px — sharp brand corners (intentional)
        lg: "0.25rem",        // 4px
        xl: "0.5rem",         // 8px — cards
        "2xl": "1rem",        // 16px
        full: "9999px",       // TRUE pill/circle — FIXED from 0.75rem
        circle: "50%",        // Perfect circle (for logo-badge)
      },
      spacing: {
        "xxs": "0.25rem",
        "xs": "0.5rem",
        "sm": "0.75rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "2xl": "3rem",
        "3xl": "4.5rem",
        "4xl": "6rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3rem",
        "gutter": "1.5rem",
      },
      fontFamily: {
        "display": ["Sora", "sans-serif"],
        "display-mobile": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-lg": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "label-mono": ["Space Grotesk", "monospace"],
      },
      fontSize: {
        "display": ["56px", { lineHeight: "68px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.14em", fontWeight: "600" }],
      },
      animation: {
        "spin-slow": "spin 16s linear infinite",
        "spin-medium": "spin 8s linear infinite",
        "aurora": "aurora 20s ease-in-out infinite",
        "glint": "glint 3s ease-in-out infinite",
        "count-shimmer": "shimmer 2s ease-in-out infinite",
      },
      keyframes: {
        aurora: {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(30px, -30px) scale(1.05)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.97)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        glint: {
          "0%, 100%": { transform: "translateY(-100%)", opacity: "0" },
          "50%": { transform: "translateY(100%)", opacity: "1" },
        },
      },
      backgroundImage: {
        "gold-cyan": "linear-gradient(135deg, #eac078, #5bdfff)",
        "gold-shine": "linear-gradient(90deg, transparent, rgba(234,192,120,0.4), transparent)",
        "navy-radial": "radial-gradient(ellipse at 50% 0%, rgba(91,223,255,0.08) 0%, transparent 70%)",
      },
      boxShadow: {
        "gold-sm": "0 0 12px rgba(234,192,120,0.25)",
        "gold": "0 0 20px rgba(234,192,120,0.35), 0 0 40px rgba(234,192,120,0.15)",
        "gold-lg": "0 0 40px rgba(234,192,120,0.5), 0 0 80px rgba(234,192,120,0.2)",
        "cyan": "0 0 20px rgba(91,223,255,0.35), 0 0 40px rgba(91,223,255,0.15)",
        "glass": "0 8px 32px rgba(0,0,0,0.4), inset 0 1px 0 rgba(234,192,120,0.08)",
        "card-hover": "0 16px 48px rgba(0,0,0,0.5), 0 0 30px rgba(234,192,120,0.12)",
      },
      transitionTimingFunction: {
        "brand": "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      transitionDuration: {
        "micro": "200ms",
        "standard": "400ms",
        "slow": "700ms",
      },
    },
  },
  plugins: [],
};
